services:
  - type: web
    name: dental-patient-manager-frontend
    env: static
    staticPublishPath: dist
    buildCommand: npm install && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
