services:
  - type: web
    name: smilehub-pro-frontend
    env: static
    staticPublishPath: dist
    buildCommand: npm install && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin

  - type: web
    name: smilehub-pro-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: DATABASE_URL
        sync: false # Set this in the Render dashboard with your Neon Postgres connection string
      - key: JWT_SECRET
        sync: false # Set this in the Render dashboard with a strong secret
      - key: NODE_ENV
        value: production
      - key: AI_SERVICE_URL
        value: https://your-ai-service-url.render.com # Update when you deploy AI service
    autoDeploy: true
    healthCheckPath: /api/health
    region: oregon
